### ISSUE TITLE
UserWarning: Using a target size that is different to the input size is deprecated

### ISSUE THREAD

**Issue by ken-avco** [PranY/Passion-Projects#1]
PranY-

Thanks for documenting these use cases for structured data!

I get an error when using your code with no changes.

m.lr_find()

gives:

C:\Users\marti\Anaconda3\envs\fastai\lib\site-packages\torch\nn\functional.py:1189: UserWarning: Using a target size (torch.Size([512])) that is different to the input size (torch.Size([512, 1])) is deprecated. Please ensure they have the same size.
  "Please ensure they have the same size.".format(target.size(), input.size()))

Does the code still work for you after updating FastAI with git pull? Any ideas of why this error? Thanks!

**Comment by PranY** [comment]
Apologies for the super late response, I never got this notification somehow. I remember that the code worked perfectly when I wrote it but it's possible that something changed as fastai evolves very quickly. I don't think I have an equivalent notebook for v2 but your question above simply points to "unsqueeze(0)" on the targets.
